# Generated by Django 4.2.4 on 2023-08-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_task_breaks_remove_task_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='pomodoros_completed',
            new_name='pomegranates_completed',
        ),
    ]
