# Generated by Django 4.2.4 on 2023-08-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_pomodoros_completed_status_pomegranates_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='status',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
    ]
